name: flutter_a11y
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  accessibility_tools: ^2.4.1
  device_info_plus: any
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^2.6.1


dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
